services:
  portfolio-api:
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      # - redis
      - postgres
    environment:
      - POSTGRES_DB_URI="postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DATABASE}"
    networks:
      - app-network
    env_file:
      - ${ENV_FILE_NAME}
    command: ${STARTUP_COMMAND}

  #  if you use cloud db then do comment out the redis service

  # redis:
  #   image: redis
  #   container_name: ${REDIS_CONTAINER}
  #   networks:
  #     - app-network
  #   expose:
  #     - ${REDIS_PORT}

  #  if you use cloud db then do comment out the postgres service

  # postgres:
  #   container_name: ${POSTGRES_CONTAINER}
  #   image: postgres
  #   networks:
  #     - app-network
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USERNAME}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DATABASE}
  #   restart: always
  #   volumes:
  #     - postgres-volume:/var/lib/postgresql/data
  #   ports:
  #     - ${POSTGRES_EXPOSE_PORT}:${POSTGRES_PORT}

networks:
  app-network:
    driver: bridge
#  if you use cloud db then do comment out the postgres service
# volumes:
#   postgres-volume:
#     external: false
#     name: ${POSTGRES_VOLUME}
