services:
  portfolio-api:
    volumes:
      - ./:/${APP_DIR}
      - /${APP_DIR}/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command:
      [
        'npx',
        'nodemon',
        '--watch',
        'src',
        '--exec',
        'ts-node',
        './src/server.ts',
      ]
